FROM ubuntu:16.04

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y software-properties-common
RUN apt-get install -y tmux curl git man unzip vim wget
RUN apt-get install -y flex bison autoconf automake autotools-dev
RUN apt-get install -y curl libmpc-dev libmpfr-dev libgmp-dev gawk
RUN apt-get install -y build-essential bison flex texinfo gperf
RUN apt-get install -y libtool patchutils bc zlib1g-dev

ENV HOME /home
WORKDIR /home

# verilator simulator
ENV verilator_ver 3.904
ENV verilator_top ${HOME}/verilator
ENV verilator_ins ${verilator_top}/install
ENV verilator_dir ${verilator_top}/verilator-${verilator_ver}
ENV verilator_web http://www.veripool.org/ftp/verilator-${verilator_ver}.tgz
ENV verilator_tar ${verilator_top}/verilator-${verilator_ver}.tar.gz

RUN mkdir -p ${verilator_top}
RUN mkdir -p ${verilator_ins}

RUN wget ${verilator_web} -O ${verilator_tar}
RUN tar xf ${verilator_tar} -C ${verilator_top}
RUN cd ${verilator_dir} && ./configure --prefix=${verilator_ins}
RUN make -C ${verilator_dir} verilator_bin
RUN make -C ${verilator_dir} installbin installdata

# ariane riscv-fesvr
ENV fesvr_ver caffc16f703de16866f5d49daaaf3f474900b9a7
ENV fesvr_dir ${HOME}/riscv-fesvr
ENV fesvr_ins ${fesvr_dir}/install
ENV fesvr_bld ${fesvr_dir}/build
ENV LD_LIBRARY_PATH ${fesvr_ins}/lib
RUN git clone https://github.com/pulp-platform/riscv-fesvr.git ${fesvr_dir}
RUN git -C ${fesvr_dir} checkout ${fesvr_ver} -b cse548
RUN mkdir -p ${fesvr_bld} ${fesvr_ins}
RUN cd ${fesvr_bld} && ../configure --prefix=${fesvr_ins}
RUN make -C ${fesvr_bld} install

# riscv gnu toolchain
ENV toolchain_ver b4dae89f85bf882852c6186b1284df11065bfcd9
ENV toolchain_dir ${HOME}/riscv-gnu-toolchain
ENV toolchain_bld ${toolchain_dir}/build
ENV RISCV ${toolchain_dir}/install
ENV PATH ${RISCV}/bin:${PATH}
RUN git clone --depth=50 https://github.com/riscv/riscv-gnu-toolchain.git ${toolchain_dir}
RUN git -C ${toolchain_dir} checkout ${toolchain_ver} -b cse548
RUN git -C ${toolchain_dir} submodule update --init --recursive
RUN mkdir -p ${toolchain_bld}
RUN cd ${toolchain_bld} && ${toolchain_dir}/configure --prefix=${RISCV}
RUN cd ${toolchain_bld} && make

RUN cd ${HOME}

CMD ["bash"]
