dockerfile = $(abspath .)/Dockerfile
docker_image_name = cse548

verilator_version = 3.904

default: build

build:
	docker build -f $(dockerfile) -t $(docker_image_name) .

run:
	docker run -it $(docker_image_name)
